name: testing
on: push

jobs:
    test_projects:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run page unit tests
              run: |
               python3 tests.py
